DROP TABLE IF EXISTS #ISSUED
DROP TABLE IF EXISTS #USED

SELECT *
INTO #ISSUED
FROM COUPON_ISSUE
WHERE CTP_CODE LIKE '%CON%' AND CPN_STATUS <> 'C' AND MAIN_IDENTIFIER_NO <> '1080000020'  AND TRN_DATE BETWEEN '2024-10-01' AND '2024-11-25'


SELECT *,
        CASE WHEN TRN_STORE = 'S888' THEN 'E-COM'
        WHEN TRN_STORE LIKE 'M%' THEN 'MEGAHOME'
        WHEN TRN_STORE LIKE 'XP%' THEN 'FAIR'
        ELSE 'HOMEPRO' END AS STORE_GROUP
INTO #USED
FROM COUPON_USED
WHERE CTP_CODE LIKE '%CON%' AND TRN_TYPE = 'CV' AND TRN_STATUS = 'B' AND MAIN_IDENTIFIER_NO <> '1080000020'  AND TRN_DATE BETWEEN '2024-10-01' AND '2024-11-25'

-----------------------------------------RAW -----------------------------------------
SELECT A.CTP_CODE, A.CTP_NAME_TH, A.MAIN_IDENTIFIER_NO, A.CPN_ID AS ISSUED, A.TRN_DATE AS ISSUED_DATE, 
        B.CPN_ID AS 'USED', B.TRN_DATE AS USED_DATE, B.TRN_FULL_TICKET_NO, B.TRN_STORE_SHT, B.TRN_STORE_NAME,  B.TRN_TOTAL_VALUE AS SALES, TRD_DISCOUNT AS DISCOUNT
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID





-----------------------------------------BY STORE -----------------------------------------
SELECT A.CTP_CODE, A.CTP_NAME_TH, B.TRN_STORE_SHT, B.TRN_STORE_NAME, COUNT(A.CPN_ID) AS ISSUED, COUNT(B.CPN_ID) AS 'USED', SUM(B.TRN_TOTAL_VALUE) AS SALES, SUM(TRD_DISCOUNT) AS DISCOUNT
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID
GROUP BY A.CTP_CODE, A.CTP_NAME_TH, B.TRN_STORE_SHT, B.TRN_STORE_NAME
ORDER BY CTP_CODE

---------------------------------------- SUMMARY ----------------------------------------
SELECT A.CTP_CODE, A.CTP_NAME_TH, COUNT(A.CPN_ID) AS ISSUED
        ,COUNT(B.CPN_ID) AS 'USED'
        ,CAST((COUNT(B.CPN_ID) * 1.00 / COUNT(A.CPN_ID)) AS REAL) AS '%USED' 
        ,SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS TOTAL_SALES
        ,SUM(B.TRN_TOTAL_VALUE) AS SALES
        ,SUM(TRD_DISCOUNT) AS DISCOUNT
        ,AVG(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS BASKET
        ,CAST((SUM(TRD_DISCOUNT) * 1.00 / SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) ) AS REAL) AS '%COST/SALES' 
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID
GROUP BY A.CTP_CODE, A.CTP_NAME_TH
ORDER BY CTP_CODE


-------------------------------------- SUMMARY BY MONTH -------------------------------------
SELECT 'TOTAL' AS MONTH, COUNT(A.CPN_ID) AS ISSUED
        ,COUNT(B.CPN_ID) AS 'USED'
        ,CAST((COUNT(B.CPN_ID) * 1.00 / COUNT(A.CPN_ID) ) AS REAL) AS '%USED' 
        ,SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS TOTAL_SALES
        ,SUM(B.TRN_TOTAL_VALUE) AS SALES
        ,SUM(TRD_DISCOUNT) AS DISCOUNT
        ,AVG(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS BASKET
        ,CAST((SUM(TRD_DISCOUNT) * 1.00 / SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT)) AS REAL) AS '%COST/SALES' 
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID

UNION

SELECT CAST(MONTH(A.TRN_DATE) AS char) AS MONTH, COUNT(A.CPN_ID) AS ISSUED
        ,COUNT(B.CPN_ID) AS 'USED'
        ,CAST((COUNT(B.CPN_ID) * 1.00 / COUNT(A.CPN_ID) ) AS REAL) AS '%USED' 
        ,SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS TOTAL_SALES
        ,SUM(B.TRN_TOTAL_VALUE) AS SALES
        ,SUM(TRD_DISCOUNT) AS DISCOUNT
        ,AVG(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS BASKET
        ,CAST((SUM(TRD_DISCOUNT) * 1.00 / SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) ) AS REAL) AS '%COST/SALES' 
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID
GROUP BY MONTH(A.TRN_DATE)


-------------------------------------- SUMMARY BY STORE GROUP --------------------------------------
SELECT 'TOTAL' AS STORE_GROUP, COUNT(A.CPN_ID) AS ISSUED
        ,COUNT(B.CPN_ID) AS 'USED'
        ,CAST((COUNT(B.CPN_ID) * 1.00 / COUNT(A.CPN_ID) ) AS REAL) AS '%USED' 
        ,SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS TOTAL_SALES
        ,SUM(B.TRN_TOTAL_VALUE) AS SALES
        ,SUM(TRD_DISCOUNT) AS DISCOUNT
        ,AVG(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS BASKET
        ,CAST((SUM(TRD_DISCOUNT) * 1.00 / SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT)) AS REAL) AS '%COST/SALES' 
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID

UNION

SELECT STORE_GROUP
        , COUNT(A.CPN_ID) AS ISSUED
        ,COUNT(B.CPN_ID) AS 'USED'
        ,CAST((COUNT(B.CPN_ID) * 1.00 / COUNT(A.CPN_ID) ) AS REAL) AS '%USED' 
        ,SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS TOTAL_SALES
        ,SUM(B.TRN_TOTAL_VALUE) AS SALES
        ,SUM(TRD_DISCOUNT) AS DISCOUNT
        ,AVG(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) AS BASKET
        ,CAST((SUM(TRD_DISCOUNT) * 1.00 / SUM(B.TRN_TOTAL_VALUE + TRD_DISCOUNT) ) AS REAL) AS '%COST/SALES' 
FROM #ISSUED AS A
LEFT JOIN #USED AS B
ON A.CPN_ID = B.CPN_ID
GROUP BY STORE_GROUP
