-- 1000 คนแรก ที่พ้อยสูงสุดตามลำดับ
------------------------------- STORE MOST VISIT -------------------------------
DROP TABLE IF EXISTS #RANK
SELECT *
    ,CAST(RANK() OVER(PARTITION BY RWD_CARD_NO ORDER BY VISIT DESC) AS INT) AS RANK_STORE
    ,CAST(RANK() OVER(PARTITION BY RWD_CARD_NO ORDER BY SALES DESC) AS INT) AS RANK_SALES
INTO #RANK
FROM    (SELECT RWD_CARD_NO, STORE,COUNT(DISTINCT BILLING_DATE) AS VISIT, SUM(NET_ITEM_AMT) AS SALES
        FROM sas..TRN_BILLING_ITEM_CAR_BASE
        WHERE BILLING_DATE BETWEEN '2020-01-01' AND '2024-12-31' AND RWD_CARD_NO IS NOT NULL AND STORE NOT IN ('S001','S002','S004','S007','S087','S088','S089','S092','S094','S801','S802'
        ) AND STORE NOT LIKE ('S88%') AND STORE NOT LIKE ('XP%')
        GROUP BY RWD_CARD_NO, STORE) AS A


DROP TABLE IF EXISTS #MOST
SELECT RWD_CARD_NO, STORE, VISIT, SALES, RANK_STORE, RANK_SALES, MAX(SALES) AS MOST_SALES
INTO #MOST
FROM #RANK AS A
WHERE A.RANK_STORE = 1
GROUP BY RWD_CARD_NO,STORE, VISIT, SALES, RANK_STORE, RANK_SALES
ORDER BY A.RWD_CARD_NO


DROP TABLE IF EXISTS #MOST_VISIT
SELECT *
INTO #MOST_VISIT
FROM (SELECT *,ROW_NUMBER() OVER(PARTITION BY RWD_CARD_NO ORDER BY MOST_SALES DESC) AS ROW_SALES FROM #MOST) AS A
WHERE ROW_SALES = 1
ORDER BY RWD_CARD_NO


------------------------------- POINT EXP -------------------------------
DROP TABLE IF EXISTS #POINT_EXP
SELECT MAIN_IDENTIFIER_NO, TIER_NAME, SUM(POINT_VALUE-POINT_SPENT) AS POINT_EXP
INTO #POINT_EXP
FROM sas..CLM_TRN_POINT_CAR_BASE
WHERE MAIN_BALANCE_FLAG = 1 AND (POINT_EXP_DATE BETWEEN '2024-12-12' AND '2024-12-31') AND POINT_VALUE >=0 AND POINT_STATUS_NAME not in ('Not booked','Cancelled')
GROUP BY MAIN_IDENTIFIER_NO, TIER_NAME


------------------------------- RESULT -------------------------------
SELECT B.MAIN_IDENTIFIER_NO, FIRST_NAME, ADR_MOBILE, STORE, POINT_EXP
FROM #MOST_VISIT AS A
INNER JOIN (SELECT * FROM #POINT_EXP WHERE POINT_EXP >= 100 ) AS B
ON A.RWD_CARD_NO = B.MAIN_IDENTIFIER_NO
INNER JOIN (SELECT * FROM sas..CLM_MST_CUSTOMER_CAR_BASE WHERE C_TELESALES = 'Y' AND C_ANALYTICS = 'Y' AND C_DIRECT_MARKETING = 'Y' AND ADR_MOBILE IS NOT NULL) AS C
ON A.RWD_CARD_NO = C.MAIN_IDENTIFIER_NO
ORDER BY POINT_EXP DESC
