DROP TABLE IF EXISTS #BILL
DROP TABLE IF EXISTS #TIER_SALES
SELECT DISTINCT RWD_CARD_NO, MONTH(BILLING_DATE) AS MONTH, STORE, IDENTIFIER_CODE, TICKET_NO, SUM(NET_ITEM_AMT) AS SALES
INTO #BILL
FROM BILLING AS A
LEFT JOIN (SELECT MAIN_IDENTIFIER_NO, IDENTIFIER_CODE FROM IDENTIFIER
            WHERE IDENTIFIER_CODE = 'PRO') AS B
ON A.RWD_CARD_NO = B.MAIN_IDENTIFIER_NO
WHERE RWD_CARD_NO IS NOT NULL AND (BILLING_DATE BETWEEN '2024-11-01' AND '2025-01-28')
GROUP BY RWD_CARD_NO, IDENTIFIER_CODE, STORE, TICKET_NO, MONTH(BILLING_DATE)



SELECT RWD_CARD_NO, STORE, IDENTIFIER_CODE, TICKET_NO, SALES, MONTH
     ,CASE WHEN SALES <= 0  THEN 'RETURN'
          WHEN SALES <= 999 THEN 'G01_1 - 999'
          WHEN SALES <= 1999 THEN 'G02_1,000 - 1,999'
          WHEN SALES <= 2499 THEN 'G03_2,000 - 2,499'
          WHEN SALES <= 2999 THEN 'G04_2,500 - 2,999'
          WHEN SALES <= 3999 THEN 'G05_3,000 - 3,999'
          WHEN SALES <= 4999 THEN 'G06_4,000 - 4,999'
          WHEN SALES <= 5999 THEN 'G07_5,000 - 5,999'
          WHEN SALES <= 6999 THEN 'G08_6,000 - 6,999'
          WHEN SALES <= 7999 THEN 'G09_7,000 - 7,999'
          WHEN SALES <= 8999 THEN 'G10_8,000 - 8,999'
          WHEN SALES <= 9999 THEN 'G11_9,000 - 9,999'
          WHEN SALES <= 11999 THEN 'G12_10,000 - 11,999'
          WHEN SALES <= 13999 THEN 'G13_12,000 - 13,999'
          WHEN SALES <= 19999 THEN 'G14_14,000 - 19,999'
          WHEN SALES <= 24999 THEN 'G15_20,000 - 24,999'
          WHEN SALES <= 29999 THEN 'G16_25,000 - 29,999'
          WHEN SALES <= 34999 THEN 'G17_30,000 - 34,999'
          WHEN SALES <= 39999 THEN 'G18_35,000 - 39,999'
          WHEN SALES <= 49999 THEN 'G19_40,000 - 49,999'
          WHEN SALES <= 69999 THEN 'G20_50,000 - 69,999'
          WHEN SALES <= 79999 THEN 'G21_70,000 - 79,999'
          WHEN SALES <= 99999 THEN 'G22_80,000 - 99,999'
          WHEN SALES <= 149999 THEN 'G23_100,000 - 149,999'
          WHEN SALES <= 199999 THEN 'G24_150,000 - 199,999'
          WHEN SALES <= 299999 THEN 'G25_200,000 - 299,999'
          WHEN SALES <= 499999 THEN 'G26_300,000 - 499,999'
          WHEN SALES <= 999999 THEN 'G27_500,000 - 999,999'
          WHEN SALES >= 1000000 THEN 'G28 1,000,000.-'
          END AS TIER_SALES
INTO #TIER_SALES
FROM #BILL

-- Homepro & Megahome ---------------------------------------------------------
SELECT 'Total' AS TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'M%' OR STORE LIKE 'S%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%'

UNION


SELECT TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'M%' OR STORE LIKE 'S%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%'
GROUP BY TIER_SALES
ORDER BY TIER_SALES


-- Homepro ------------------------------------------------------------------------------------
SELECT 'Total' AS TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'S%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%'

UNION


SELECT TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'S%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%'
GROUP BY TIER_SALES
ORDER BY TIER_SALES


-- Megahome & Procard ------------------------------------------------------------------------------------
SELECT 'Total' AS TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'M%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%' AND IDENTIFIER_CODE = 'PRO'

UNION


SELECT TIER_SALES, COUNT(DISTINCT RWD_CARD_NO) AS MEMBER,COUNT(DISTINCT TICKET_NO) AS TICKET,SUM(SALES) AS SALES
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN RWD_CARD_NO END) AS MEMBER_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '11' THEN TICKET_NO END) AS TICKET_11
      ,SUM( CASE WHEN MONTH = '11' THEN SALES END) AS SALES_11
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN RWD_CARD_NO END) AS MEMBER_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '12' THEN TICKET_NO END) AS TICKET_12
      ,SUM( CASE WHEN MONTH = '12' THEN SALES END) AS SALES_12
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN RWD_CARD_NO END) AS MEMBER_1
      ,COUNT(DISTINCT CASE WHEN MONTH = '1' THEN TICKET_NO END) AS TICKET_1
      ,SUM( CASE WHEN MONTH = '1' THEN SALES END) AS SALES_1
FROM #TIER_SALES
WHERE STORE LIKE 'M%' AND STORE NOT IN ('S888', 'M888') AND STORE NOT LIKE 'S88%' AND IDENTIFIER_CODE = 'PRO'
GROUP BY TIER_SALES
ORDER BY TIER_SALES
