------------------ Duplicate ----------------------
DROP TABLE IF EXISTS #DUP
SELECT MAIN_IDENTIFIER_NO, COUNT(*) AS T_TICK
INTO #DUP
FROM POINT_RULE
WHERE BUSINESS_RULE_CODE LIKE 'BRETAX250103W' 
GROUP BY MAIN_IDENTIFIER_NO
HAVING COUNT(*)> 1


DROP TABLE IF EXISTS #RETURN
SELECT DISTINCT ORG_TICKET_NO
INTO #RETURN
FROM TICKET
WHERE ORG_TICKET_NO IN (SELECT TICKET_NO
                        FROM sas..CLM_TRN_POINT_BRULE_CAR_BASE
                        WHERE BUSINESS_RULE_CODE LIKE 'BRETAX250103W'
                            AND MAIN_IDENTIFIER_NO IN (SELECT MAIN_IDENTIFIER_NO FROM #DUP))


-- Overview ----------------------------------------------------------------------------------------------------------------------------------------
SELECT 'TOTAL' AS WALLET_TIER, COUNT(DISTINCT MAIN_IDENTIFIER_NO) AS MEMBER, SUM(POINT_VALUE) AS WALLET_EARN, SUM(POINT_SPENT)/100 AS WALLET_SPEND
        ,SUM(POINT_VALUE)-(SUM(POINT_SPENT)/100) AS WALLET_AVAILABLE
        ,AVG(POINT_SPENT)/100 AS WALLET_AVG_SPEND
        ,AVG(POINT_VALUE-(POINT_SPENT)/100) AS WALLET_AVG_AVAILABLE
        ,COUNT(DISTINCT CASE WHEN POINT_STATUS = 'S' THEN MAIN_IDENTIFIER_NO END) AS MEMBER_FULL_SPEND
        ,COUNT(DISTINCT CASE WHEN POINT_STATUS = 'B' THEN MAIN_IDENTIFIER_NO END) AS MEMBER_AVAILABLE
FROM POINT AS A
INNER JOIN (SELECT TICKET_NO
            FROM POINT_RULE
            WHERE BUSINESS_RULE_CODE = 'BRETAX250103W') AS B
ON A.TICKET_NO = B.TICKET_NO
WHERE POINT_TYPE = 'WALLET' AND POINT_VALUE > 0 AND TRN_DATE > '2024-01-01'
    AND TRN_TYPE_NAME NOT IN ('Return','Reversal','Redemption Refund', 'Take loan') AND POINT_STATUS_NAME NOT IN ('Cancelled','Not booked') 
    AND TRN_STATUS_NAME NOT IN ('For Approval','Rejected','Reversed')
    AND A.TICKET_NO NOT IN (SELECT * FROM #RETURN)

UNION

SELECT CAST(POINT_VALUE AS CHAR) AS WALLET_TIER, COUNT(DISTINCT MAIN_IDENTIFIER_NO) AS MEMBER, SUM(POINT_VALUE) AS WALLET_EARN, SUM(POINT_SPENT)/100 AS WALLET_SPEND 
        ,SUM(POINT_VALUE)-(SUM(POINT_SPENT)/100) AS WALLET_AVAILABLE
        ,AVG(POINT_SPENT)/100 AS WALLET_AVG_SPEND
        ,AVG(POINT_VALUE-(POINT_SPENT)/100) AS WALLET_AVG_AVAILABLE
        ,COUNT(DISTINCT CASE WHEN POINT_STATUS = 'S' THEN MAIN_IDENTIFIER_NO END) AS MEMBER_FULL_SPEND
        ,COUNT(DISTINCT CASE WHEN POINT_STATUS = 'B' THEN MAIN_IDENTIFIER_NO END) AS MEMBER_AVAILABLE
FROM POINT AS A
INNER JOIN (SELECT TICKET_NO
            FROM POINT_RULE
            WHERE BUSINESS_RULE_CODE = 'BRETAX250103W') AS B
ON A.TICKET_NO = B.TICKET_NO
WHERE POINT_TYPE = 'WALLET' AND POINT_VALUE > 0 AND TRN_DATE > '2024-01-01'
    AND TRN_TYPE_NAME NOT IN ('Return','Reversal','Redemption Refund', 'Take loan') AND POINT_STATUS_NAME NOT IN ('Cancelled','Not booked') 
    AND TRN_STATUS_NAME NOT IN ('For Approval','Rejected','Reversed')
    AND A.TICKET_NO NOT IN (SELECT * FROM #RETURN)
GROUP BY POINT_VALUE


-- Raw ;----------------------------------------------------------------------------------------------------
SELECT MAIN_IDENTIFIER_NO, TRN_DATE, STORE, A.TICKET_NO AS FROM_TICKET, TRN_TOTAL_VALUE AS FROM_SALES, POINT_VALUE AS WALLET_EARN, POINT_SPENT/100 AS WALLET_SPEND 
FROM POINT AS A
INNER JOIN (SELECT TICKET_NO
            FROM POINT_RULE
            WHERE BUSINESS_RULE_CODE = 'BRETAX250103W') AS B
ON A.TICKET_NO = B.TICKET_NO
WHERE POINT_TYPE = 'WALLET' AND POINT_VALUE > 0 AND TRN_DATE > '2024-01-01'
    AND TRN_TYPE_NAME NOT IN ('Return','Reversal','Redemption Refund', 'Take loan') AND POINT_STATUS_NAME NOT IN ('Cancelled','Not booked') 
    AND TRN_STATUS_NAME NOT IN ('For Approval','Rejected','Reversed')
    AND A.TICKET_NO NOT IN (SELECT * FROM #RETURN)





